---
- name: "Run workload iterations"
  ansible.builtin.include_tasks: tasks/run_iteration_tasks.yaml
  loop: "{{ range(1, (workload.benchmark_runs | default(benchmark_runs) | int) + 1) | list }}"
  loop_control:
    label: "Run {{ item }}"
    loop_var: run_iteration
